# Generated by Django 4.2.16 on 2024-10-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
